* Deep Rationality

A [[https://github.com/GregDavidson/loel/blob/main/Devel/creating-curricula.org][Curriculum]] of /LOEL/, the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]].

We recommend reading this document slowly, a few sections at a time.
Pause, reflect, browse resources, come back for more.

You may also find some of these [[file:RESOURCES.org][Resources on Deep Rationality]] to be of
interest.

** What Deep Rationality Offers

Deep Rationality offers
- freedom from attachments based on past upsets
- clarity to discover what really matters to us
- the possibility of inventing inspiring futures to live towards

** What Deep Rationality Doesn't Offer
- Training in Valid Reasoning
- for this see the [[https://github.com/GregDavidson/DATDA#readme][LOEL Curriculum on Rationality]]

Rationality and Deep Rationality work well together, despite being quite
distinct.

At the logical level, irrationality can lead to us making mistakes
about our understanding of the world and our strategies for meeting
our goals.

At the deeper level, irrationality can lead us to fundamentally
misunderstand ourselves and our values.  Beliefs are even more of an
issue at this deeper level, as they become connected with our identity
and we hide them from ourselves.  Contradictions to our beliefs tend
to make us hold to them more tightly, carefully not looking at them
critically.

** Fundamental Deep Rationality Distinctions

/Deep Rationality/ is directed by distinctions that are
- of primary importance to all human beings
- poorly addressed by mainstream culture and education
- presented in confused forms by most religious and spiritual teachings
- addressed in sophisticated forms by specialized philosophers
      - who use specialized academic language
- therefore: Not very accessible to most human beings!

The primary experience of all Human Beings is /Subjective/, not /Objective/
- Our existence in the world has an immediate quality
      - /What it's like to be us/ is immediately experienced
      - that's hard to explain

We learn to interpret much of what we experience as being about
- /Entities In The World/
      - sensory experiences help us parse the world into /objects/
      - we identify
            - the presence of those objects
            - their stable characteristics
            - their current situation and changeable properties
- /Ourselves/
      - our body - much like other /objects in the world/
      - our thoughts and feelings

It's easy to make the mistake of
- interpreting ourselves as just another object in the world
- with stable characteristics, e.g. our body and mental machinery
- with properties, including our thoughts and feelings

Why is this a mistake?
- We are what is doing the interpretation
- The interpretations we create are models
- /A map is not the territory it described!/

Than what are we?
- We are /Subjects/ rather than /Objects/
- We are the /Source/ of our /Interpretations/
- We are the /Context/ witnessing and interpreting the /Content/
- We are Human /Beings/ experiencing
      - the Quality of /Being in the World/ along Evolving Time

** So What? - Briefly

What's wrong with identifying ourselves as an Object?

An Object is defined by its
- stable characteristics
- known properties whose values change in limited ways

Objects don't have any inherent meaning, purpose or dignity

Subjects have
- a Quality of Being
- what it's like to Be Themselves
- an Authentic Self

Subjects are always and naturally
- Creating Interpretations
- Creating and Discovering Meaning

When we are present to our authentic self, we have the power to
- notice our values
- create goals which are congruent with our values
- authentically discard or change goals
- discover/create our life purpose

** So What? - At Greater Length

When we model a Human Being as an Object
- they become a stereotype
- we interpret them as being limited
- we create an illusion of predictability
- we lose the richness of their full being

When we model ourselves as an Object
- we become a stereotype to ourselves
- we interpret ourselves as being limited
- we expect our future to be consistent with our past
- (we may experience being trapped!)
- we lose the richness of our full being
- we lose the ability to /Create New Futures!/

Experiencing our immediate quality of Being
- is fresh, energizing
- cuts through our objectifications
- reveals where we've become trapped by attachments

Buddhism identifies the source of suffering as Attachment
- to our interpretations
- to our points of view
- to our thoughts and feelings
- to Belief Systems
- to any Content

Attachments turn us into Objects.

Key practices of Deep Rationality are
- noticing constraints in the Quality of our Being
- identifying attachments
- letting go of those attachments
- engaging with our new freedom of being
- rediscovering our /Authentic Self/

Shared Belief Systems can be difficult to distinguish
- they seem to just be "how reality is"
- (This is how superstitions operate!)
- Diversity in our community can be very helpful!
- Exposing ourselves to the new can be very helpful!

Deep Rationality is grounded in Being.
- Being exists only in the moment.
- Being is at the root of our life.

Much of our time we have our attention on the content of our life
- We easily lose awareness of /How We're Being/.
- Of the quality of being who we are in this moment.
- We forget who we are
- We unintentionally undermine the quality of our life
- We may feel like somethings off, something important is missing

Deep Rationality tools are designed to allow us to periodically
- free our attention somewhat from
      - what we're doing
      - our thoughts
      - our feeling
- create some distance between
      - the processes going on in our body and our mind
      - allowing us to notice what it's like
            - to be present to those processes
            - to be present to ourselves
- notice any attachments coloring the quality of who we're being

Deep Rationality is an access to
- clarity
- authenticity
- integrity of being

** Culture and Memes Own You!

Cultures largely consist of vast overlapping and nested collections of
memes.  As a social animal with language, you and they have
co-evolved, i.e. human beings have slowly evolved to enhance their
receptiveness to being colonized by networks of memes and those
networks of memes undergo rapid evolution to enhance their their
ability to colonize human beings!

[[https://en.wikipedia.org/wiki/Meme][Memes]] are the smallest units of meaning which can be transmitted from
one person to another, typically by human language, but also by music,
art, behavior, etc.  Most memes make little impression on the
recipient and are not retained very long.  Some other memes change the
direction of the recipient's life profoundly.

Memes replicate by being transmitted.  Errors in transmission cause
variations.  Memes compete with one another for the limited memory and
attentional resources of the recipient's brain - your brain.  Memes
which do a better job of holding your attention or installing
themselves in your memory are "fitter" than competing memes - does
this start to sound familiar?

Memes are replicators which mutate and are subject to [[https://en.wikipedia.org/wiki/Natural_selection][Natural
Selection]] much like genes are.  Indeed, it was the evolutionary
biologist Richard Dawkins who noticed this resemblance and introduced
them in a chapter of his enlightening little book [[https://en.wikipedia.org/wiki/The_Selfish_Gene][The Selfish Gene]].
Memetic evolution works on a /much/ faster time scale than genetic
evolution, although with human beings the two go together.  The human
mind emerges in part from the partnership of the human brain and its
vast network of memes.  (Another key element is Consciousness - which
no one understands very well!)

/an aside:/

Many otherwise rational people who hold [[https://en.wikipedia.org/wiki/Progressivism][Progressive]] /Beliefs/ - as
distinct from /Progressive Values/ - consider [[https://en.wikipedia.org/wiki/Richard_Dawkins][Richard Dawkins]] and
especially his book /The Selfish Gene/ to be [[https://en.wikipedia.org/wiki/Anathema][Anathema]].  This is a
great example of how belief systems can undermine our integrity and
values.  Many rational thinkers with good values and important ideas
have been subject to [[https://en.wikipedia.org/wiki/Cancel_culture][Cancel Culture]] by people who claim to be
progressive.  People who entangle their beliefs with their personal
and social identities become enemies of their own needs and values!

/Back to memes:/

Memes do not act on their own, any more than words in a sentence are
acting on their own.  Memes form coalitions in order to more
efficiently acquire your brain's (and mind's) resources.  Memes within
such coalitions attach themselves to your [[file:nvc-feelings-and-needs-inventory.pdf][Fundamental Human Feelings
And Needs]].

[[https://en.wikipedia.org/wiki/Mindfulness][Mindfulness Meditation]] is very useful to observing the memes and meme
coalitions which have colonized us and how they effect us.

** Deep Rationality Resources

- [[https://touchpuuhonua.github.io/SomeClues/][Some Clues For You]]!

*** Books, Audio Recordings, Videos

Books make it easier for you as the Reader to pause and reflect.  Deep
Rationality books should usually be read slowly, a few pages or
sections at a time.  It can be useful to write down questions,
insights, etc.

Audio Recordings and Videos have a fixed presentation rate which you
mostly have to adapt to.  This can inhibit reflection.  See if you can
pause them fairly often.  It can be useful to record your questions
and insights as audio or (ideally) written notes to deepen the
inquiry.

Find others who are interested in similar inquiry, growth and
development.  Discuss your questions and insights with them.

Reflect on your insights:
- What would be available in my life if I were to fully realize this
  insight?
- How can seize the opportunity to live into this new future?

The [[https://en.wikipedia.org/wiki/Works_by_Alan_Watts][Books and Audio Recordings of Alan Watts]]
- a treasure of Deep Rationality
- Alan Watts has made much of South and East Asian Deep Rationality
  accessible to everyone

*Nonviolent (Compassionate) Communication*  aka NVC Materials
- /Nonviolent Communication: A Language of Life/ by Marshall Rosenberg
- /Nonviolent Communication Companion Workbook/ by Lucy Leu
  - Guides individuals and informal groups in studying Nonviolent
    Communication
- Lots of other books, recordings and videos

*** Workshops

The [[https://www1.hai.org][Human Awareness Institute]] Workshops.

[[https://www.landmarkworldwide.com][Landmark Worldwide]]'s workshops, especially
- Their original /Curriculum for Living/
      - The Landmark Forum
      - The Landmark Advanced Course
      - The Self-Expression and Leadership Program
            - do not miss this last part of the Curriculum!
- their other workshops and curricula are also valuable
  - e.g. their /Communication/, /Wisdom/ and /Leadership/ tracks.
- Note: Landmark is often criticized for their "sales" techniques.
  Whether this bothers you or not, they are truly a treasure.

NVC Workshops and Study Groups
- In addition to reading books about NVC, especially
  - /Nonviolent Communication: A Language of Life/ by NVC's founder
  - and its companion book
it can be useful to go deeper through
- Workshops taught by experienced NVC Facilitators (Caveat Emptor)
- Informal reading groups.

NVC Study Groups are quite nice:
- You meet with a group of friends once a week or every-other week
  - in one another's homes or a pleasant [[https://en.wiktionary.org/wiki/third_place#English][Third Place]]
- For each meeting you
  - focus on one chapter in the (or each) book
    - either just Marshall Rosenberg's /A Language of Life/
    - or both that and Lucy Liu's /Companion Workbook/
      - they have corresponding chapters
  - engage with the current chapter's material in your daily life
    between meetings
  - share with your friends about what you're discovering

*** Relevant Philosophical Traditions

Deep Rationality was very important to Early Philosophers. Some more recent
Philosophers have continued to explore Deep Rationality.

- [[https://plato.stanford.edu/entries/socrates/][Socrates]]
- [[https://en.wikipedia.org/wiki/Stoicism][Stoicism]]
      - See [[https://www.gutenberg.org/ebooks/2680][Meditations]] by the Emperor of Rome, [[https://en.wikipedia.org/wiki/Marcus_Aurelius][Marcus Aurelius]]
- [[https://en.wikipedia.org/wiki/Existentialism][Existentialism]]
- [[https://en.wikipedia.org/wiki/Ontology][Ontology]]

Warning: Approaching these philosophical subjects only intellectually
will only cultivate a narrow intellectual mode of being which, despite
its value for purely intellectual inquiry, fundamentally alienates us
from being present to the quality of our experience of being - which
is highly ironic! One must carefully balance these intellectual
inquiries with experiential inquiries and notice where and how they
can assist with the quality of such.

*** Spiritual Communities and Traditions

Many spiritual communities have developed profound and effective tools
for accessing and practicing Deep Rationality. Alas, many of these
traditions have collapsed some of their Deep Rationality distinctions
with belief systems and/or authoritarian practices from the
surrounding cultures over time. Collapsed distinctions can be
confusing, especially for those who have not practiced Deep
Rationality outside of such traditions.

Those of us who have a strong practice of Deep Rationality free of
spiritual traditions may discover that such traditions offer great
treasure. Of especial note are
- Many forms of Buddhism, especially Zen Buddhism
- Taoism
- Sufism, distinct from other forms of Islam

A good test for whether a system of Deep Rationality is free of
excessive attachments is to see if it is consistent with regular
Rationality, Scientific Inquiry and the values of [[https://en.wikipedia.org/wiki/Age_of_Enlightenment][The European
Enlightenment]], the sources of so much of the freedom and awesomeness
of the modern world.

** [[https://en.wikipedia.org/wiki/Know_thyself][Know Thyself]]

Your body (including your mind) is your vehicle in this life.  It has
a particular design with needs, drives, emotions, sexual and gender
orientations, cognitive limitations, biases and more.

What relationship with your body and your mind will support your
power, freedom and authenticity?
