* Deep Rationality

A [[https://github.com/GregDavidson/loel/blob/main/Devel/creating-curricula.org][Curriculum]] of /LOEL/, the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]].

We recommend reading this document slowly, a few sections at a time.
Pause, reflect, browse resources, come back for more.

Explore some of these
- [[file:RESOURCES.org][Resources on Deep Rationality]]

** What Deep Rationality Offers

Deep Rationality offers
- Freedom :: from attachments based on past upsets.
- Clarity :: to discover what really matters to us.
- Possibilities :: for inventing inspiring futures to live towards.

** What Deep Rationality Doesn't Offer
- Training in Valid Reasoning
- for this see the [[https://github.com/GregDavidson/DATDA#readme][LOEL Curriculum on Rationality]]

Rationality and Deep Rationality work well together, despite being
logically distinct.

At the logical level, irrationality can lead to us making mistakes
about our understanding of the world and our strategies for meeting
our goals.

At the deeper level, irrationality can lead us to fundamentally
misunderstand ourselves and our values.  Beliefs are even more of an
issue at this deeper level, as they become connected with our identity
and we hide them from ourselves.  Contradictions to our beliefs tend
to make us hold to them more tightly, carefully not looking at them
critically.

** Fundamental Deep Rationality Distinctions

/Deep Rationality/ consists of distinctions that are
- of primary importance to all human beings
- poorly addressed by mainstream culture and education
- presented in confused forms by most religious and spiritual teachings
- addressed in sophisticated forms by specialized philosophers
      - who use specialized academic language
- therefore: Not very accessible to most human beings!

The primary experience of all Human Beings is /Subjective/, not /Objective/
- Our existence in the world has an immediate quality
      - /What it's like to be us/ is immediately experienced
      - [[https://en.wikipedia.org/wiki/Hard_problem_of_consciousness][that's hard to explain!]]

We learn to interpret much of what we experience as being about
- /Objects In The World/
- We learn to parse Sensory Experience into /Objects/!
We identify /Objects:/
- the presence of those objects
- what state they are in
  - the properties that shouldn't change
  - the properties which change, and how

It's easy to make the mistake of
- interpreting Ourselves as just another /Object In The World/
- with stable characteristics, e.g. our body and mind
- containing elements, including our thoughts and feelings

Why is this a mistake?
- We are what is doing the interpretation
- The interpretations we create are models
- /A map is not the territory it described!/

Than what are we?
- We are /Subjects/ rather than /Objects/
- We are the /Source/ of our /Interpretations/
- We are the /Context/ witnessing and interpreting the /Content/
- We are Human /Beings/ experiencing
      - the Quality of /Being in the World/ along Evolving Time

Thoughts and Feelings have /no natural persistence!/
- No more than images in the eye or sounds in the ear!
- Appearances of persistence are actually reactivations
  - Which take active work on the part of the brain/mind!
- If you stop /giving attention/ to any thought or feeling
  - It will almost immediately disappear!

More details on this in the section on /Memes/ below.

** So What? - Briefly

What's wrong with identifying ourselves as an Object?

An Object is defined by its
- stable characteristics
- known properties whose values change in limited ways

Objects don't have any inherent meaning, purpose or dignity

Subjects have
- a Quality of Being
- what it's like to Be Themselves
- an Authentic Self

Subjects are always and naturally
- Creating Interpretations
- Creating and Discovering Meaning

When we are present to our authentic self, we have the power to
- notice our values
- create goals which are congruent with our values
- authentically discard or change goals
- discover/create our life purpose

** So What? - At Greater Length

When we model a Human Being as an Object
- they become a stereotype
- we interpret them as being limited
- we create an illusion of predictability
- we lose the richness of their full being

When we model ourselves as an Object
- we become a stereotype to ourselves
- we interpret ourselves as being limited
- we expect our future to be consistent with our past
- (we may experience being trapped!)
- we lose the richness of our full being
- we lose the ability to /Create New Futures!/

Experiencing our immediate quality of Being
- is fresh, energizing
- cuts through our objectifications
- reveals where we've become trapped by attachments

Buddhism identifies the source of suffering as Attachment
- to our interpretations
- to our points of view
- to our thoughts and feelings
- to Belief Systems
- to any Content

Attachments turn us into Objects.

Key practices of Deep Rationality are
- noticing constraints in the Quality of our Being
- identifying attachments
- letting go of those attachments
- engaging with our new freedom of being
- rediscovering our /Authentic Self/

Shared Belief Systems can be difficult to distinguish
- they seem to just be "how reality is"
- (This is how superstitions operate!)
- Diversity in our community can be very helpful!
- Exposing ourselves to the new can be very helpful!

Deep Rationality is grounded in Being.
- Being exists only in the moment.
- Being is at the root of our life.

Much of our time we have our attention on the content of our life
- We easily lose awareness of /How We're Being/.
- Of the quality of being who we are in this moment.
- We forget who we are
- We unintentionally undermine the quality of our life
- We may feel like somethings off, something important is missing

Deep Rationality tools are designed to allow us to periodically
- free our attention somewhat from
      - what we're doing
      - our thoughts
      - our feeling
- create some distance between
      - the processes going on in our body and our mind
      - allowing us to notice what it's like
            - to be present to those processes
            - to be present to ourselves
- notice any attachments coloring the quality of who we're being

Deep Rationality is an access to
- clarity
- authenticity
- integrity of being

** Culture and Memes Own You!

Cultures largely consist of vast overlapping and nested collections of
memes.  As a social animal with language, you and they have
co-evolved, i.e. human beings have slowly evolved to enhance their
receptiveness to being colonized by networks of memes and those
networks of memes undergo rapid evolution to enhance their their
ability to colonize human beings!

[[https://en.wikipedia.org/wiki/Meme][Memes]] are the smallest units of meaning which can be transmitted from
one person to another, typically by human language, but also by music,
art, behavior, etc.  Most memes make little impression on the
recipient and are not retained very long.  Some other memes change the
direction of the recipient's life profoundly.

Memes replicate by being transmitted.  Errors in transmission cause
variations.  Memes compete with one another for the limited memory and
attentional resources of the recipient's brain - your brain.  Memes
which do a better job of holding your attention or installing
themselves in your memory are "fitter" than competing memes - does
this start to sound familiar?

Memes are replicators which mutate and are subject to [[https://en.wikipedia.org/wiki/Natural_selection][Natural
Selection]] much like genes are.  Indeed, it was the evolutionary
biologist Richard Dawkins who noticed this resemblance and introduced
them in a chapter of his enlightening little book [[https://en.wikipedia.org/wiki/The_Selfish_Gene][The Selfish Gene]].
Memetic evolution works on a /much/ faster time scale than genetic
evolution, although with human beings the two go together.  The human
mind emerges in part from the partnership of the human brain and its
vast network of memes.  (Another key element is Consciousness - which
no one understands very well!)

/an aside:/

Many otherwise rational people who hold [[https://en.wikipedia.org/wiki/Progressivism][Progressive]] /Beliefs/ - as
distinct from /Progressive Values/ - consider [[https://en.wikipedia.org/wiki/Richard_Dawkins][Richard Dawkins]] and
especially his book /The Selfish Gene/ to be [[https://en.wikipedia.org/wiki/Anathema][Anathema]].  This is a
great example of how belief systems can undermine our integrity and
values.  Many rational thinkers with good values and important ideas
have been subject to [[https://en.wikipedia.org/wiki/Cancel_culture][Cancel Culture]] by people who claim to be
progressive.  People who entangle their beliefs with their personal
and social identities become enemies of their own needs and values!

/Back to memes:/

Memes do not act on their own, any more than words in a sentence are
acting on their own.  Memes form coalitions in order to more
efficiently acquire your brain's (and mind's) resources.  Memes within
such coalitions attach themselves to your [[file:nvc-feelings-and-needs-inventory.pdf][Fundamental Human Feelings
And Needs]].

[[https://en.wikipedia.org/wiki/Mindfulness][Mindfulness Meditation]] is very useful to observing the memes and meme
coalitions which have colonized us and how they effect us.

** [[https://en.wikipedia.org/wiki/Know_thyself][Know Thyself]]

Your body (including your mind) is your vehicle in this life.  It has
a particular design with needs, drives, emotions, sexual and gender
orientations, cognitive limitations, biases and more.

What relationship with your body and your mind will support your
power, freedom and authenticity?
