- Γνῶθι σαυτόν :: [[https://en.wikipedia.org/wiki/Know_thyself][Know thyself]]

*** Philosophy

Many schools and individual works of philosophy from many times and cultures are
inquiries into our nature as human beings intended to support the possibility of
us leading good and possibly great lives.

*** Evolutionary Psychology

The structure of our physical bodies emerge from an evolved developmental
program. This includes our brains and everything else in or bodies which
constitutes the substrate of our mind and emotions. (Consciousness is still a
mystery which is generally left alone by evolutionary psycholoy until our
understanding is ready to address it.)

Understanding how evolution our mind and emotion

*** Cognitive Science, Psychology and Neurophysiology

Cognitive Science studies Cognitive (Mental) systems in general. This includes
Human and Animal Minds and Emotional Systems as well as Artificial Models of
such things.

Cognitive Psychology focuses on the nature of the "Human Information Processing
System", i.e. our Sensory Systems, Motor Systems, Emotional Systems, Reasoning
Systems, etc.

Some other branches of Psychology complement Cognitive Psychology in an overall
effort to model all aspects of the human mind in the most general sense.

Neurophysiology attempts to understand how the structure and function, including
subdivisions of animal nervous systems accounts for all or almost all
perception, processing and behavior in all animals.

Our understanding of all of these matters has been illuminated by an attempt to
build artificially intelligent systems in the form of electronic computers.

| Animal          | Computer                       |
|-----------------+--------------------------------|
| Neurophysiology | Multi-Level Electronics        |
| Sensation       | Multi-Stage Input Processing   |
| Behavior        | Multi-Stage Output Processing  |
| Memory          | Database Systems               |
| Intelligence    | Pattern Matching and Reasoning |


*** Logic and Rationality

Logic and Rationality stand on Deep Rationality.  See the curriculum
- [[https://github.com/GregDavidson/Rationality#readme][LOEL Rationality Curriculum]]
